# Generated by Django 2.0.4 on 2018-10-31 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rg', models.CharField(blank=True, max_length=255, null=True)),
                ('emissor', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=255, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('mae', models.CharField(blank=True, max_length=255, null=True)),
                ('pai', models.CharField(blank=True, max_length=255, null=True)),
                ('email_responsavel', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img_alunos')),
                ('agencia', models.CharField(blank=True, max_length=50, null=True)),
                ('conta', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('contato', models.TextField(blank=True, null=True)),
                ('pcd', models.BooleanField(default=False)),
                ('cid', models.CharField(blank=True, max_length=50, null=True)),
                ('pcd_descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('Autorizado', 'Autorizado'), ('Efetuado', 'Efetuado')], default='Autorizado', max_length=30)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Autorizações de saída',
                'ordering': ['-data', 'matricula__aluno'],
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFalta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('descricao', models.CharField(max_length=150)),
                ('artigo', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Categoria das Faltas',
            },
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('ocorrencia_email_aluno', models.BooleanField(default=True)),
                ('ocorrencia_email_responsavel_aluno', models.BooleanField(default=True)),
                ('ocorrencia_email_responsavel_user', models.BooleanField(default=True)),
                ('ocorrencia_email_responsavel_setor', models.BooleanField(default=True)),
                ('ocorrencia_email_coordenacao_curso', models.BooleanField(default=True)),
                ('encaminhamento_email_aluno', models.BooleanField(default=True)),
                ('encaminhamento_email_responsavel_aluno', models.BooleanField(default=True)),
                ('encaminhamento_email_responsavel_user', models.BooleanField(default=True)),
                ('encaminhamento_email_responsavel_setor', models.BooleanField(default=True)),
                ('encaminhamento_email_coordenacao_curso', models.BooleanField(default=True)),
                ('providencia_encaminhamento_email_aluno', models.BooleanField(default=True)),
                ('providencia_encaminhamento_email_responsavel_aluno', models.BooleanField(default=True)),
                ('providencia_encaminhamento_email_responsavel_user', models.BooleanField(default=True)),
                ('providencia_encaminhamento_email_responsavel_setor', models.BooleanField(default=True)),
                ('providencia_encaminhamento_email_coordenacao_curso', models.BooleanField(default=True)),
                ('autorizacao_email_aluno', models.BooleanField(default=True)),
                ('autorizacao_email_responsavel_aluno', models.BooleanField(default=True)),
                ('autorizacao_email_responsavel_user', models.BooleanField(default=True)),
                ('autorizacao_email_responsavel_setor', models.BooleanField(default=True)),
                ('autorizacao_email_coordenacao_curso', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Configurações do sistema',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('descricao', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('ie', models.CharField(blank=True, max_length=45, null=True)),
                ('im', models.CharField(blank=True, max_length=45, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('cidade', models.CharField(blank=True, max_length=150, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('fone', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('site', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='img_empresa')),
                ('responsavel_ocorrencia', models.CharField(max_length=150)),
                ('email_responsavel_ocorrencia', models.EmailField(max_length=254)),
                ('responsavel_sistema', models.CharField(max_length=150)),
                ('email_responsavel_sistema', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Empresa',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('providencias', models.TextField(blank=True, null=True)),
                ('outras_informacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Encaminhado', 'Encaminhado'), ('Atendido', 'Atendido')], default='Encaminhado', max_length=30)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa')),
            ],
            options={
                'verbose_name_plural': 'Encaminhamentos',
                'ordering': ['-data', 'matricula__aluno'],
            },
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('descricao', models.TextField()),
                ('inciso', models.CharField(max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.CategoriaFalta')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faltas',
                'ordering': ['categoria__artigo'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('ano_letivo', models.IntegerField(default=2018)),
                ('token', models.CharField(blank=True, max_length=9, null=True)),
                ('token_limite', models.DateField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Aluno')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa')),
            ],
            options={
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-ano_letivo', 'turma', 'aluno'],
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('data', models.DateField()),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa')),
                ('falta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Falta')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Matricula')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data', 'matricula__aluno'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Serviços',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='ServicoCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('descricao', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorias de serviços',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('descricao', models.CharField(max_length=150)),
                ('turno', models.CharField(max_length=150)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Curso')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.IntegerField(blank=True, null=True)),
                ('aluno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Aluno')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='servico',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.ServicoCategoria'),
        ),
        migrations.AddField(
            model_name='servico',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa'),
        ),
        migrations.AddField(
            model_name='servico',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Matricula'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='responsavel_providencias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel_providencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Servico'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa'),
        ),
        migrations.AddField(
            model_name='curso',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriafalta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa'),
        ),
        migrations.AddField(
            model_name='categoriafalta',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banco',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa'),
        ),
        migrations.AddField(
            model_name='banco',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa'),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Matricula'),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='user_confirma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_confirma', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aluno',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Banco'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
