# Generated by Django 2.0.4 on 2018-11-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='disciplina',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
