# Generated by Django 2.0 on 2017-12-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20171221_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Curso'),
            preserve_default=False,
        ),
    ]
