# Generated by Django 2.0.4 on 2019-04-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190403_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='providencia_ocorrencia_email_aluno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='providencia_ocorrencia_email_coordenacao_curso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='providencia_ocorrencia_email_responsavel_aluno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='providencia_ocorrencia_email_responsavel_setor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='providencia_ocorrencia_email_responsavel_user',
            field=models.BooleanField(default=True),
        ),
    ]
