# Generated by Django 2.0.4 on 2019-04-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190403_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='providencias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
