# Generated by Django 2.0 on 2017-12-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20171222_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['descricao']},
        ),
    ]
