# Generated by Django 2.0 on 2017-12-22 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20171222_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Turma'),
            preserve_default=False,
        ),
    ]
