# Generated by Django 2.0.4 on 2019-04-03 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_ocorrencia_providencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='falta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Falta'),
        ),
    ]
