# Generated by Django 2.0.4 on 2019-04-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20190403_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(choices=[('Registrada', 'Registrada'), ('Retornada', 'Retornada'), ('Enviada', 'Enviada'), ('Arquivada', 'Arquivada')], default='Registrada', max_length=30),
        ),
    ]
