# Generated by Django 2.0 on 2017-12-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_aluno_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='descricao',
            field=models.CharField(max_length=150),
        ),
    ]
