# Generated by Django 2.0.4 on 2019-04-25 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0007_auto_20190416_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('data_inicial', models.DateField()),
                ('tempo_afastamento', models.IntegerField()),
                ('descricao', models.TextField()),
                ('motivo_indeferimento', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Deferido', 'Deferido'), ('Indeferido', 'Indeferido')], default='Solicitado', max_length=30)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Matricula')),
                ('responsavel_analise_justificativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel_analise_justificativa', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Justificativas',
                'ordering': ['-data_inicial', 'matricula__aluno'],
            },
        ),
    ]
