# Generated by Django 2.0.4 on 2019-04-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_justificativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativa',
            name='status',
            field=models.CharField(choices=[('Solicitada', 'Solicitada'), ('Deferida', 'Deferida'), ('Indeferida', 'Indeferida')], default='Solicitada', max_length=30),
        ),
    ]
