# Generated by Django 2.0 on 2018-03-08 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0008_ocorrencia_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'ordering': ['data'], 'verbose_name_plural': 'Ocorrências'},
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='turma',
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Aluno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='matricula',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Matricula'),
            preserve_default=False,
        ),
    ]
