# Generated by Django 2.0 on 2018-03-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20180308_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AddField(
            model_name='matricula',
            name='ano_letivo',
            field=models.IntegerField(default=2018),
        ),
    ]
