# Generated by Django 2.0.4 on 2019-04-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20190424_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='justificativa_email_aluno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='justificativa_email_retorno_aluno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='justificativa_email_setor',
            field=models.BooleanField(default=True),
        ),
    ]
