# Generated by Django 2.0 on 2018-03-13 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0010_auto_20180310_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFalta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('descricao', models.CharField(max_length=150)),
                ('artigo', models.IntegerField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categoria das Faltas',
            },
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('descricao', models.TextField()),
                ('inciso', models.CharField(max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.CategoriaFalta')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faltas',
            },
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['-ano_letivo', 'turma', 'aluno'], 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'ordering': ['-data', 'matricula__aluno'], 'verbose_name_plural': 'Ocorrências'},
        ),
    ]
