# Generated by Django 2.0 on 2018-03-13 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20180313_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='falta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Falta'),
            preserve_default=False,
        ),
    ]
