# Generated by Django 2.0.3 on 2018-03-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20180320_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email_responsavel_ocorrencia',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email_responsavel_sistema',
            field=models.EmailField(max_length=254),
        ),
    ]
