# Generated by Django 2.0.3 on 2018-03-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20180320_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='user',
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
