# Generated by Django 2.0.4 on 2018-06-20 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20180620_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encaminhamento',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='analise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='outras_informacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='providencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='responsavel_analise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel_analise', to=settings.AUTH_USER_MODEL),
        ),
    ]
