# Generated by Django 2.0.4 on 2018-06-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20180620_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
