# Generated by Django 2.0.4 on 2018-08-04 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0022_encaminhamento_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('Autorizado', 'Autorizado'), ('Cancelado', 'Cancelado'), ('Efetuado', 'Efetuado'), ('Pendente', 'Pendente')], default='Pendente', max_length=30)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Matricula')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Autorizações',
                'ordering': ['-data', 'matricula__aluno'],
            },
        ),
    ]
