# Generated by Django 2.0.4 on 2018-08-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_autorizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacao',
            name='status',
            field=models.CharField(choices=[('Autorizado', 'Autorizado'), ('Efetuado', 'Efetuado')], default='Pendente', max_length=30),
        ),
    ]
