# Generated by Django 2.0.4 on 2018-08-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_auto_20180804_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorizacao',
            options={'ordering': ['-data', 'matricula__aluno'], 'verbose_name_plural': 'Autorizações de saída'},
        ),
        migrations.AlterField(
            model_name='autorizacao',
            name='descricao',
            field=models.TextField(default='Teste'),
            preserve_default=False,
        ),
    ]
