# Generated by Django 2.0.4 on 2018-08-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_auto_20180806_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacao',
            name='email_aluno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='email_coordenacao',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='email_responsavel_aluno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='email_responsavel_encaminhamento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='email_aluno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='email_coordenacao',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='email_responsavel_aluno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='email_responsavel_encaminhamento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='email_aluno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='email_coordenacao',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='email_responsavel_aluno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='email_responsavel_ocorrencia',
            field=models.BooleanField(default=True),
        ),
    ]
