# Generated by Django 2.0.4 on 2018-08-07 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0027_auto_20180807_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('ocorrencia_email_aluno', models.BooleanField(default=True)),
                ('ocorrencia_email_responsavel_aluno', models.BooleanField(default=True)),
                ('ocorrencia_email_responsavel_user', models.BooleanField(default=True)),
                ('ocorrencia_email_responsavel_setor', models.BooleanField(default=True)),
                ('ocorrencia_email_coordenacao_curso', models.BooleanField(default=True)),
                ('encaminhamento_email_aluno', models.BooleanField(default=True)),
                ('encaminhamento_email_responsavel_aluno', models.BooleanField(default=True)),
                ('encaminhamento_email_responsavel_user', models.BooleanField(default=True)),
                ('encaminhamento_email_responsavel_setor', models.BooleanField(default=True)),
                ('encaminhamento_email_coordenacao_curso', models.BooleanField(default=True)),
                ('autorizacao_email_aluno', models.BooleanField(default=True)),
                ('autorizacao_email_responsavel_aluno', models.BooleanField(default=True)),
                ('autorizacao_email_responsavel_user', models.BooleanField(default=True)),
                ('autorizacao_email_responsavel_setor', models.BooleanField(default=True)),
                ('autorizacao_email_coordenacao_curso', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='autorizacao',
            name='email_aluno',
        ),
        migrations.RemoveField(
            model_name='autorizacao',
            name='email_coordenacao',
        ),
        migrations.RemoveField(
            model_name='autorizacao',
            name='email_responsavel_aluno',
        ),
        migrations.RemoveField(
            model_name='autorizacao',
            name='email_responsavel_encaminhamento',
        ),
        migrations.RemoveField(
            model_name='encaminhamento',
            name='email_aluno',
        ),
        migrations.RemoveField(
            model_name='encaminhamento',
            name='email_coordenacao',
        ),
        migrations.RemoveField(
            model_name='encaminhamento',
            name='email_responsavel_aluno',
        ),
        migrations.RemoveField(
            model_name='encaminhamento',
            name='email_responsavel_encaminhamento',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='email_aluno',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='email_coordenacao',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='email_responsavel_aluno',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='email_responsavel_ocorrencia',
        ),
    ]
