# Generated by Django 2.0.4 on 2018-08-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auto_20180822_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='status',
            field=models.CharField(choices=[('Encaminhado', 'Encaminhado'), ('Atendido', 'Atendido')], default='v', max_length=30),
        ),
    ]
