# Generated by Django 2.0.4 on 2018-08-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_encaminhamento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encaminhamento',
            name='status',
        ),
    ]
