# Generated by Django 2.0.4 on 2018-08-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_remove_encaminhamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='status',
            field=models.CharField(choices=[('Encaminhado', 'Encaminhado'), ('Atendido', 'Atendido')], default='Encaminhado', max_length=30),
        ),
    ]
