# Generated by Django 2.0.4 on 2018-08-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_encaminhamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='providencia_encaminhamento_email_aluno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='providencia_encaminhamento_email_coordenacao_curso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='providencia_encaminhamento_email_responsavel_aluno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='providencia_encaminhamento_email_responsavel_setor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='providencia_encaminhamento_email_responsavel_user',
            field=models.BooleanField(default=True),
        ),
    ]
