# Generated by Django 2.0.4 on 2018-09-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_aluno_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='responsavel',
            new_name='mae',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='pai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='rg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
