# Generated by Django 2.0.4 on 2018-09-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_auto_20180928_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='emissor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
