# Generated by Django 2.0.4 on 2018-09-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_auto_20180928_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
