# Generated by Django 2.0.4 on 2018-10-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_auto_20180928_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aluno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Aluno'),
        ),
    ]
