# Generated by Django 2.0.4 on 2018-10-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_userprofile_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='siape',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
