# Generated by Django 2.0.4 on 2018-10-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_auto_20181002_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='numero_matricula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
