# Generated by Django 2.0.4 on 2018-10-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_aluno_numero_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='contato',
            field=models.TextField(blank=True, null=True),
        ),
    ]
