# Generated by Django 2.0.4 on 2018-10-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_auto_20181005_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaminhamento',
            name='data',
            field=models.DateField(),
        ),
    ]
