# Generated by Django 2.0.4 on 2018-10-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_auto_20181005_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.CharField(default='INTEGRAL', max_length=150),
            preserve_default=False,
        ),
    ]
