# Generated by Django 2.0.4 on 2018-10-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_turma_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='pcd',
            field=models.BooleanField(default=False),
        ),
    ]
