# Generated by Django 2.0.4 on 2018-10-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_auto_20181019_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='pcd_descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
