# Generated by Django 2.0.4 on 2018-10-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0047_aluno_pcd_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='token',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='token_limite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
